name: flujo de trabajo
on:
  push:
    branches:
      - master
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: step1-job1
      run: echo "hola mundo-job1"
  job2:
    runs-on: ubuntu-latest
    steps:
    - name: step1-job2
      run: echo "hola mundo-job2"
  job3:
    runs-on: ubuntu-latest
    needs: [job2]
    steps:
    - name: step1-job3
      run: echo "hola mundo-job2"
    - name: step2-job3
      run: |
        touch primero.txt
        echo "hola primero" >> primero.txt
    - name: checkout
      uses: actions/checkout@v2
    - name: ls
      run: |
        chmod +x script.sh
        ./script.sh
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: "23.20.200.57"
        username: "ec2-user"
        key: ${{ secrets.SSHKEY }}
        port: 22
        script: | 
          ls
        
