name: Hola Mundo
on:
  - push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: step1-job1
      run: echo "hola mundo-job1"
  job2:
    runs-on: ubuntu-latest
    steps:
    - name: step1-job2
      run: echo "hola mundo-job2"
  job3:
    runs-on: ubuntu-latest
    needs: [job2]
    steps:
    - name: step1-job2
      run: echo "hola mundo-job2"